name: async_toolkit
description: A comprehensive Dart package for async programming with cancellation tokens, timeout management, retry mechanisms, parallel execution, and rate limiting (throttle/debounce).
version: 1.0.0
homepage: https://github.com/duymainek/async_toolkit
repository: https://github.com/duymainek/async_toolkit
issue_tracker: https://github.com/duymainek/async_toolkit/issues
documentation: https://pub.dev/documentation/async_toolkit/latest/

environment:
  sdk: '>=3.0.0 <4.0.0'

# No dependencies - pure Dart implementation
dependencies:

dev_dependencies:
  test: ^1.25.0
  lints: ^4.0.0

# Platform support
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - async
  - cancellation
  - timeout
  - retry
  - parallel
  - throttle
  - debounce
  - utilities
  - concurrency
  - rate-limiting

funding:
  - https://github.com/sponsors/duymainek